language: python
python:
  - "3.8"
branches:
  only:
    - production
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test gameplay
  - python manage.py test functional_tests
