# Generated by Django 3.0.7 on 2020-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_auto_20200627_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='location',
            field=models.CharField(blank=True, choices=[('AM', 'Antrim'), ('AH', 'Armagh'), ('CW', 'Carlow'), ('CN', 'Cavan'), ('CE', 'Clare'), ('CK', 'Cork'), ('DY', 'Derry'), ('DL', 'Donegal'), ('DN', 'Down'), ('DB', 'Dublin'), ('FH', 'Fermanagh'), ('GY', 'Galway'), ('KY', 'Kerry'), ('KE', 'Kildare'), ('KK', 'Kilkenny'), ('LS', 'Laois'), ('LM', 'Leitrim'), ('LK', 'Limerick'), ('LN', 'London'), ('LD', 'Longford'), ('LH', 'Louth'), ('MO', 'Mayo'), ('MH', 'Meath'), ('MN', 'Monaghan'), ('NY', 'New York'), ('OY', 'Offaly'), ('RN', 'Roscommon'), ('SO', 'Sligo'), ('TY', 'Tipperary'), ('TE', 'Tyrone'), ('WD', 'Waterford'), ('WH', 'Westmeath'), ('WX', 'Wexford'), ('WW', 'Wicklow')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='region',
            field=models.CharField(choices=[('C', 'Connacht'), ('L', 'Leinster'), ('M', 'Munster'), ('U', 'Ulster'), ('A', 'All-Ireland')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('AM', 'Antrim'), ('AH', 'Armagh'), ('CW', 'Carlow'), ('CN', 'Cavan'), ('CE', 'Clare'), ('CK', 'Cork'), ('DY', 'Derry'), ('DL', 'Donegal'), ('DN', 'Down'), ('DB', 'Dublin'), ('FH', 'Fermanagh'), ('GY', 'Galway'), ('KY', 'Kerry'), ('KE', 'Kildare'), ('KK', 'Kilkenny'), ('LS', 'Laois'), ('LM', 'Leitrim'), ('LK', 'Limerick'), ('LN', 'London'), ('LD', 'Longford'), ('LH', 'Louth'), ('MO', 'Mayo'), ('MH', 'Meath'), ('MN', 'Monaghan'), ('NY', 'New York'), ('OY', 'Offaly'), ('RN', 'Roscommon'), ('SO', 'Sligo'), ('TY', 'Tipperary'), ('TE', 'Tyrone'), ('WD', 'Waterford'), ('WH', 'Westmeath'), ('WX', 'Wexford'), ('WW', 'Wicklow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('C', 'Connacht'), ('L', 'Leinster'), ('M', 'Munster'), ('U', 'Ulster'), ('A', 'All-Ireland')], max_length=100),
        ),
        migrations.AlterField(
            model_name='topscorer',
            name='region',
            field=models.CharField(choices=[('C', 'Connacht'), ('L', 'Leinster'), ('M', 'Munster'), ('U', 'Ulster'), ('A', 'All-Ireland')], max_length=100),
        ),
    ]
