# Generated by Django 3.0.7 on 2020-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20200627_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='finalists',
            field=models.ManyToManyField(related_name='entry_finalists', to='gameplay.Finalist'),
        ),
    ]
