# Generated by Django 3.0.7 on 2020-07-22 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_auto_20200629_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='position',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('fixture', 'prediction'), name='unique prediction'),
        ),
    ]
